{"name": "Авторизация с неверным логином или паролем", "status": "passed", "description": "При неуспешной авторизации возвращает HTTP 401 и сообщение об ошибке", "steps": [{"name": "Отправка POST на auth/login", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'qclements@example.org', 'password': 'abracadabra'}"}], "start": 1718264927082, "stop": 1718264927359}], "parameters": [{"name": "field", "value": "'password'"}], "start": 1718264927082, "stop": 1718264927360, "uuid": "1f9b87ec-3209-47a3-baeb-d1787aa0b3eb", "historyId": "b1d56c4f69aec7832ff6274084af568a", "testCaseId": "7bdec89f1358e664b0e3c7770a6f7a71", "fullName": "tests.test_auth_login.TestLoginUser#test_login_wrong_email_or_pass", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_login"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "XPMEPODW0067"}, {"name": "thread", "value": "30908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_login"}]}