{"name": "Невозможность изменения данных неавторизованного пользователя, email", "status": "passed", "description": "При попытке изменения возвращает HTTP 401 и сообщение об ошибке", "steps": [{"name": "Отправка POST на auth/login", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'brent38@example.net', 'password': '437365673', 'name': 'Julie Young'}"}], "start": 1718264932801, "stop": 1718264933073}, {"name": "Отправка PATCH на auth/user", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'abracadabra', 'password': '437365673', 'name': 'Julie Young'}"}, {"name": "access_token", "value": "''"}], "start": 1718264933074, "stop": 1718264933331}], "parameters": [{"name": "field", "value": "'email'"}], "start": 1718264932800, "stop": 1718264933332, "uuid": "cbb73ffe-9160-4ab9-938c-4208eb7c2a6b", "historyId": "7b7719bfa965413a1d89dabc1cb3e74c", "testCaseId": "ed8b5b9382a269d205c24e64879389b0", "fullName": "tests.test_auth_user.TestChangeUserData#test_change_unauthorized_user_data_failure", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_user"}, {"name": "subSuite", "value": "TestChangeUserData"}, {"name": "host", "value": "XPMEPODW0067"}, {"name": "thread", "value": "30908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_user"}]}